# Generated by Django 3.2.18 on 2023-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('', 'Choose Query Subject'), ('PRODUCT', 'Product Query'), ('ORDER', 'Order Query'), ('COMMISSION', 'Commission Query'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], default='', max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('message', models.TextField(max_length=2000)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('actioned', models.BooleanField(default=False)),
            ],
        ),
    ]
