# Generated by Django 3.2.18 on 2023-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('', '--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=''),
        ),
    ]
