# Generated by Django 3.2.18 on 2023-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rated_on']},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('', '--'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=''),
        ),
    ]
