# Generated by Django 3.2.18 on 2023-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
